# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgatherer', '0002_auto_20170903_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
