# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailgatherer', '0009_auto_20170903_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='ref_id',
        ),
    ]
