# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailgatherer', '0010_remove_join_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
